[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# إذا كان عندك SPA وتحتاج كل الروتس تروح لـ index.html، فك الكومنت:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
