# netlify.toml — build & functions config

[build]
  command = ""
  publish = "dist"     # change to your site folder (e.g. "." or "public")

[functions]
  node_bundler = "esbuild"
  included_files = []

[functions."gemini-proxy"]
  timeout = 26         # Free plan ≈ 10s actual, Pro allows higher

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/gemini-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
