[build]
  command = ""
  publish = "."
[functions]
  node_bundler = "esbuild"
[functions."gemini-proxy"]
  timeout = 26
[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/gemini-proxy.js"
  status = 200
  force = true

